### ISSUE TITLE
Simulation controls panel weird behaviour when collapsing them

### ISSUE THREAD

**Issue by albertinad** [Microsoft/cordova-simulate#10]
When collapsing some control widget panel,  the content is not collapsed/hided when its container is collapsed/hided. It does not always happens, it is randomly but easy to reproduce by toggling the panels.

![screen shot 2016-04-28 at 3 23 59 pm](https://cloud.githubusercontent.com/assets/2309921/14896835/d4dada30-0d55-11e6-93ed-a8b9aaf5ad4b.png)
![screen shot 2016-04-28 at 3 24 19 pm](https://cloud.githubusercontent.com/assets/2309921/14896837/d4eaff46-0d55-11e6-96c0-48d5f01a25c1.png)

I've tested on Chrome and Firefox. In Firefox works good but not in Chrome.

**Comment by dlebu** [comment]
This was fixed by removing the collapse/expand animation effect in #38

**Comment by albertinad** [comment]
Now works great, thanks!
