### ISSUE TITLE
Is platform "windows" supported ?

### ISSUE THREAD

**Issue by udiedrichsen** [Microsoft/cordova-simulate#106]
Hi,

I tried to add Windows to the launch.json file:
        {
            "name": "Simulate Windows in browser",
            "type": "cordova",
            "request": "launch",
            "platform": "windows",
            "target": "ie",
            "simulatePort": 8000,
            "livereload": true,
            "cwd": "${workspaceRoot}"
        }

but I get always: 
[cordova-debug-adapter] Error: Unknown Platform: windows

In my project folder "platforms" exists the sub folder windows and in platforms.json:
{
    "windows": "4.4.0",
    "android": "4.1.0"
}

**Comment by TimBarham** [comment]
The windows platform is supported by `cordova-simulate`, but not by the VS Code Cordova plugin.

Microsoft/vscode-cordova#160
