### ISSUE TITLE
Camera: file picker doesn't validate that the result is a valid content

### ISSUE THREAD

**Issue by albertinad** [Microsoft/cordova-simulate#114]
When choosing a file as a response of the exec call of the plugin, or configuring the default image to use as a response, the result of selecting or cancelling picking an image is not validated. When the user cancel, the content is undefined, and an exception is thrown.

```
Uncaught TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.
```

**Comment by albertinad** [comment]
@TimBarham maybe we should include this fix as part of the new release. Sorry to merge it late!

**Comment by albertinad** [comment]
Fixed in #116

**Comment by TimBarham** [comment]
It's ok - I mainly want the `0.2.x` branch to quickly fix an issue where `cordova-simulate` can completely fail to launch from VS Code. This camera plugin fix will be in our next release from master, and I don't expect it to be too long before we update VS Code to use that.

**Comment by albertinad** [comment]
Sounds good!
