### ISSUE TITLE
cordova-number-entry fields indicate valid values are invalid

### ISSUE THREAD

**Issue by TimBarham** [Microsoft/cordova-simulate#117]
Some browsers (Chrome for example) validate the value of a numeric input field based on the value of `step`. Since this defaults to 1, and we never specify it for `cordova-number-entry` elements, any non-integer value is flagged as an error. For example, the tooltip for the Latitude field of the Geolocation panel shows something like the following error:

    Please enter a valid value. The two nearest valid values are 43 and 44.

**Comment by TimBarham** [comment]
BTW in Firefox these are shown visually as being in an error state:

![image](https://cloud.githubusercontent.com/assets/9665847/17910346/5059c3c2-693d-11e6-8d3a-f6f8e9aa0c1b.png)

**Comment by albertinad** [comment]
Yes, I noticed that too. I will fix this. Thanks!
