### ISSUE TITLE
Server module object oriented refactor broke IE

### ISSUE THREAD

**Issue by TimBarham** [Microsoft/cordova-simulate#136]
Hey @albertinad - I was just testing in IE, and noticed it is broken since the server module object oriented refactor(dbfb70d0). We get an unstyled "Geolocation" label at the top, then the geolocation map filling most of the page, with various other controls, unstyled, below it.

Any chance you could take a look? I suspect this is something to do with the WebComponents polyfill.

**Comment by albertinad** [comment]
Hi @TimBarham, sure! I will take a look at it.

**Comment by albertinad** [comment]
Fixed in #137
