### ISSUE TITLE
InAppBrowser not working with simulate in chrome

### ISSUE THREAD

**Issue by tiansivive** [Microsoft/cordova-simulate#144]
Hi!

I've been using the cordova vscode extension, which uses this lib to simulate the app in the browser. While using the cordova InAppBrowser plugin some weird behaviour occurs. I filed an issue on their repo but they recommended posting it here as well.

The problem is that the plugin doesn't seem to properly call the event handlers. I'm trying to use it for authentication purposes by capturing redirect events but it only works for the first event. After that, the handler never gets called again.

Does anyone have any idea on what the problem could be?

Here's my code:

```
private login(uri: string) {

        // Add event listener on every load (i.e. refresh), redirect is an example event
        let iBrowser = new InAppBrowser(uri, '_blank', "location=yes");
        let obs = iBrowser.on('loadstart');
        let disposable = obs.subscribe(
            (event: InAppBrowserEvent) => {

                /**This only runs on the first redirect event**/
                let foundToken = event.url.indexOf('token=');
                let foundId = event.url.indexOf('userId=');

                if (foundToken > -1 && foundId > -1) {
                    //figure out token and user ID

                    disposable.unsubscribe();
                    this.storeToken(obj.token);
                    this.nav.setRoot(Pages.Profile);
                    iBrowser.close();
                }
            })
```

**Comment by drewgillies** [comment]
Method `getCurrentUrl` in InAppBrowser is wrong--it returns the wrong url (it's a browser restriction). For security reasons, we can only get the url for as long as the contents of the iframe, and the referencing javascript, are served from the same domain (http://stackoverflow.com/questions/9788328/access-parent-window-from-iframe-cross-domain). Therefore, we don't have access to url of iframe.
