### ISSUE TITLE
[loc][Query] Possible typo in source

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/cordova-simulate#160]
Hi, we have a question from our translator. Can you help please? Thanks!

Source:
Select the default behaviour of InAppBrowser when opening using the _blank target

Open in a new window: _system target

File available here:
[https://github.com/Microsoft/cordova-simulate/blob/6ad0bd9bae9c78418db484e4796a4e04883659ef/tools/i18n/xliff/ru.xlf]

Query:
The word "target" seems to be out of place. Is this a typo? If not, can you please clarify how connects to the rest of the sentence? Thank you!

**Comment by TimBarham** [comment]
@mkyjakova - here's a screenshot of the sentence in context:

![image](https://cloud.githubusercontent.com/assets/9665847/18974944/17e711aa-86ea-11e6-82df-25ac64acba74.png)

The word `target` here refers to the name of target window when calling `InAppBrowser.open()` (which corresponds to the equivalent parameter when calling `window.open()` in JavaScript in a browser).

**Comment by TimBarham** [comment]
I'm closing the issue, but if you need further clarification feel free to re-open and ask.
