### ISSUE TITLE
How to check if running in simulator

### ISSUE THREAD

**Issue by Rainson12** [Microsoft/cordova-simulate#203]
Hey,
im having a hard time trying to figure out if im running on a native device or on the cordova-simulator. In former times i checked for "window.parent.ripple === "undefined". Is there anything likely for cordova-simulate?

**Comment by MSLaguana** [comment]
What is your purpose in trying to detect running in the simulator? We try to provide an environment that is as close to the device as we can, and inject as little additional code into the application environment as possible.

One thing that you could do is have a function like so:
```
function isSimulator(){
  cordova.exec(function (){ window.isSimulator = true;}, function () {}, "cordova-simulate", "isSimulator", []);}
}
```
When that is invoked, it would make a call to a fake plugin that doesn't exist, which would then prompt you the user to provide a value. If you specify that your response is a "success" response it will call the first callback, and your app will now know that it is running in the simulator (or has a plugin installed which responds to those dummy values I provided).

When running outside the simulator, if there is no such handler for the dummy values, then neither callback will ever be invoked and I believe that it should not impact your application.

**Comment by Rainson12** [comment]
> What is your purpose in trying to detect running in the simulator? We try to provide an environment that is as close to the device as we can, and inject as little additional code into the application environment as possible.

yea but that simply doesnt work. Most of the time either its ignoring the "app-host-handlers.js" or i just dont know how to implement it. Im running an Ionic 2 RC 3 app and I am using the AppVersion plugin:
https://github.com/whiteoctober/cordova-plugin-app-version

I have added a new folder into the plugin + app-host-handlers.js containing some simple logic so the path looks like <projectname>\plugins\cordova-plugin-app-version\src\simulation\app-host-handlers.js

and the content of the app-host-handlers.js is 
`module.exports = function (messages) {
    return {
        AppVersion: {
            getVersionCode: function (success, fail, args) {
                success(999999999);
            }
        }
    };
};`


but it is simply beeing ignored. I dont know why it shouldnt work maybe its because of typescript and webpack bundling.

**Comment by TimBarham** [comment]
@Rainson12 - you are including `app-host-handlers.js` with the plugin itself? The path to it should simply be `src\simulation` (so the `simulation` directory should be alongside the various platform directories, and `app-host-handlers.js` lives directly in that `simulation` directory).

**Comment by Rainson12** [comment]
i am including the plugin into my project and in that plugin folder there is a src folder containing the simulation folder. But for what ever reason the app-host-handlers.js is not being used
