### ISSUE TITLE
Proxy not returning the right status codes

### ISSUE THREAD

**Issue by krij0n** [Microsoft/cordova-simulate#211]
Think i found a problem with the xhr proxy. Was not getting the right status codes back from ajax calls, only getting 200 OK. Even if server responding with 500, 400, 401 and so on.

Adding this line to proxyCallback in `xhr-proxy.js` seems to help: `response.writeHead(proxyResponse.statusCode, proxyResponse.headers);`

`        var proxyCallback = function (proxyResponse) {
			response.writeHead(proxyResponse.statusCode, proxyResponse.headers);
            proxyResponse.pipe(response);
        };`

**Comment by MSLaguana** [comment]
Looks like you are right. I had thought that piping the response would pipe the headers as well, but we need to do that manually. Your suggested fix seems to be correct, I'll do up a PR with that shortly.

Thanks for pointing this out!
