### ISSUE TITLE
VS2017 RC: remote proxy not working: 'socket hang up'

### ISSUE THREAD

**Issue by nodefish** [Microsoft/cordova-simulate#215]
Hello,

I just migrated a VS Community 2015 TACO app to VS Community 2017 RC. According to [this link](https://taco.visualstudio.com/en-us/docs/vs-taco-2017-cordova-simulate/#supported-plugins), the same kind of proxy as the one from the 'Ripple emulator' is provided in cordova-simulate.

However, I can't get my app to send/receive requests to my remote development server. They time out and result in `502 - Bad Gateway`. If I look at the response in Chrome's network pane, the failed requests have this message under the response preview: `Error: socket hang up`.

I can't seem to find any proxy configuration so I'm stumped. Please advise, thanks.

**Comment by MSLaguana** [comment]
Cordova simulate does allow you to configure whether XHR requests are proxied or not, but the current VS 2017 RC does not expose that option. The next RC release will address the issue and provide a configuration option to disable the XHR proxy.

**Comment by nodefish** [comment]
I thought that regardless of configurability, it would default to true (as per this project's Readme.md). Or am I mistaken?

**Comment by MSLaguana** [comment]
It does default to true, which means that by default cordova-simulate replaces `XMLHttpRequest` in the browser with one that proxies all requests. The error that you see (`502 - Bad Gateway`) means that the connection from the proxy to the destination failed for some reason, and in this case the reason seems to be the final destination hanging up the connection.

**Comment by nodefish** [comment]
The exact same codebase works in VS2015/Ripple, though.

**Comment by MSLaguana** [comment]
When using ripple, had you disabled the XHR proxy? If so, that would explain it.

If not, cordova-simulate isn't just a fresh coat of paint on Ripple, so there could be a difference in behavior. If possible, we'd like to understand why the proxy is failing for you so we can attempt to fix it. Are you communicating with a public endpoint, or is this an internal service? We haven't been able to reproduce some of the issues with proxies such as the one you describe here, so we'd love to get more information on why it is failing for you.

**Comment by nodefish** [comment]
Yes, the endpoint is public. On Ripple, the proxy is set to `local` and not `disabled`. It also works when set to `remote`.

**Comment by MSLaguana** [comment]
Would you mind sharing the code for what you are trying to do so we can replicate the issue and try to fix it?

**Comment by nodefish** [comment]
Sure, it's basically a simple login form that gets posted via jQuery.

```
var email = _this.refs['login-input'].value;
var password = _this.refs['password-input'].value;

var formData = {
    email: encodeURIComponent(email),
    password: encodeURIComponent(password)
};

APP.session.login(formData)
.done(function (data, status, xhr) {
        if (!APP.session.currentUser.isAdmin()) {
            loadAdminPage();
        }
        else {
            loadHomePage();
        });
    }
})
.fail(function (xhr, textStatus, errorThrown) {
    dialog('login failed');
});
```

**Comment by MSLaguana** [comment]
I've played around with using ajax myself and it seems to be fine in the simple cases I've tried. It'd be a great help if you could share how your backend works. Is it a standard product that we could test against? Do you know whether the service validates any headers or something?

**Comment by nodefish** [comment]
Apologies for the delay in responding.

I've now reinstalled the entirety of VS 2017 RC and updated it, and it seems to be working now. I suspect something may have been corrupted during the initial installation.

Thanks for your help.

**Comment by pksorensen** [comment]
@MSLaguana Sorry to bother you on this old post, but been googling alot and cannot find how to disable xhr_proxy and its blocking me right now. 

I am using vs2017.

**Comment by MSLaguana** [comment]
I know that the command-line parameter is `--corsproxy=false`, but I forget how that is exposed when launching via visual studio. I believe it was in the visual studio options for cordova.

**Comment by pksorensen** [comment]
thanks @MSLaguana - there as a setting - but it was already disabled and the proxy was there anyway.

I used the commandline manually until i find a solution, tx
