### ISSUE TITLE
Ionic 2 templates don't work in Cordova Simulate with watch task in Visual Studio

### ISSUE THREAD

**Issue by TimBarham** [Microsoft/cordova-simulate#225]
**Repro steps:**
1. Download and install the Ionic 2 templates for VS 2017: http://vsixgallery.com/extension/Ionic2TemplatesVSIX.vstacotools.c74f8e7c-3c4b-43be-8a37-bdfd29bc1088/
2. Install NPM Task Runner extension: https://aka.ms/ctmhio
3. Create a new project using the Ionic 2 tabs template
4. Open the Task Runner Explorer and run the 'watch' task by double-clicking it
5. Run the application in Cordova Simulate
6. Make a change to the src\pages\home\home.html file that would be visible in the UI (e.g. change the name of a link)
7. Save changes

**Expected:**
Your change appears in the Cordova Simulate window after the watch task has run.

**Actual:**
The screen goes white in Cordova Simulate and you can't bring back the app.

**Comment by ciaran036** [comment]
@TimBarham is this fix released into the Visual Studio tooling yet? I'm on latest version of Visual Studio but was still experiencing this issue until I manually applied your fix.

**Comment by TimBarham** [comment]
@ciaran036 - yes, it should be. Can you provide your Visual Studio version details (from Help / About)? Also, if you look in 1%programdata%\Microsoft\VisualStudio\MDA\[installation id]\taco-toolset-6.3.1\versions,json1, what version of `cordova-simulate` is specified?
