### ISSUE TITLE
Chrome Workspace mapping doesnt work due to invalid paths (Ionic 2)

### ISSUE THREAD

**Issue by Rainson12** [Microsoft/cordova-simulate#230]
Due to the issue that variable contents are not beeing resolved in VS 2017 i tried to use google chrome debugger, the debugging itself works but the source mapping doesnt. When adding the local typescript files to the google chrome workspace i can not map them to the network ressources as the paths are invalid. Im not sure wether this is an ionic or a cordova-simulate issue. The paths google chrome tries to map are like:
URL PREFIX: "http://localhost:4400/build/C:\Users\USERNAME\Documents\Visual Studio 2017\Projects\SysmexSupport\SysmexSupport\src\pages\overview\overview.ts/" 

Folder Path:
/pages/overview/overview.ts/

as the URL Prefix URL is invalid the mappings dont work.

**Comment by dmitrii-snytkin** [comment]
Hello, @Rainson12 . Thanks for reporting)
I created an app through `ionic create`. Then I imported the app in VS and ran `Simulate in Browser`. In Google Chrome source mapping works fine, debug in ts files works too. Could you describe steps to reproduce this bug?

**Comment by Rainson12** [comment]
seems like this was an ionic issue and they fixed it. Thanks for trying to reproduce.
