### ISSUE TITLE
An exception is thrown when the header tag is added

### ISSUE THREAD

**Issue by cnryb** [Microsoft/cordova-simulate#237]
It's like a bug. 
The problem is serious, program execution will be interrupted.

![image](https://cloud.githubusercontent.com/assets/3817284/25881439/8585e98c-356f-11e7-832b-28f6cbc90f90.png)

[wrong program](https://github.com/Microsoft/cordova-simulate/files/988578/BlankCordovaApp16.zip)
This error demo used IDE visual studio 2017.
This wrong program uses the IDE for visual studio 2017.

**Comment by TimBarham** [comment]
Looks like there's an error in the logic that finds the `<head>` tag to insert the script references (it is also apparently inserting them in `<header>` tags).

**Comment by cnryb** [comment]
Looks like that.
But I do not know how to fix this problem.

**Comment by AleksanderStrochkov** [comment]
https://github.com/Microsoft/cordova-simulate/pull/238 - PR with fix.
