### ISSUE TITLE
Visual Studio 2017 freezing when launching simulator

### ISSUE THREAD

**Issue by neoassyrian** [Microsoft/cordova-simulate#244]
Hi all, 

Not sure why this is happening, and I can't see any error messages. Most of the times, when launching the simulator in VS2017, cordova-simulate launches chrome, and loads the site in it, however, VS freezes on the "DOM" view and never come back. I have to then kill the Chrome process for VS to return from debugging.

**Comment by neoassyrian** [comment]
![vs-simulate](https://cloud.githubusercontent.com/assets/8149804/26381819/cc2cdcfa-406a-11e7-96ab-ccf008c9ca42.JPG)

**Comment by fcampinho** [comment]
I am not sure, but I believe that this is the same as https://github.com/Microsoft/vscode-cordova/issues/259. I am still with this problem on one computer. The same project works perfectly with another computer.

**Comment by matrosov-nikita** [comment]
@neoassyrian, @fcampinho, are you still experiencing this issue? If yes, could you please provide more information about your case:

1) Does this bug reproduce if you start the simulation from CLI? (e.g., `simulate android --target=<your_target>`)?
2) What configuration settings are you using? (platform, target, ...)
3) What versions of cordova itself and plugins are you running on? (`cordova -v && cordova plugin list`)?

@fcampinho, do you get same error messages as there https://github.com/Microsoft/vscode-cordova/issues/259? It seems to me, that was Ionic specific issue.

**Comment by drewgillies** [comment]
Closing as no discussion has ensued and the above comment suggests an external cause.
