### ISSUE TITLE
deviceready has not fired after 5 seconds. chromium

### ISSUE THREAD

**Issue by dotnetCarpenter** [Microsoft/cordova-simulate#245]
No matter what I do, I can never get `simulate` to work, so in the end I created a new project to see if it was my code or if its an issue with **cordova-simulate**.

### Steps to reproduce
1. `cordova create test com.test test`
2. `cd test`
3. `cordova platforms add browser`
4. `simulate browser --target=chromium`

Error:
```
cordova.js:1051 deviceready has not fired after 5 seconds.
cordova.js:1044 Channel not fired: onNativeReady
cordova.js:1044 Channel not fired: onCordovaReady
cordova.js:1044 Channel not fired: onCordovaSimulateReady
```

OS: Ubuntu 16.04.2 LTS
cordova: 6.5.0
simulate: 0.3.12
node: v7.10.0
npm: 4.6.1

**Comment by nodefish** [comment]
I have this issue as well. I noticed the following: cordova-simulate is supposed to open 2 browser windows: 1 with the app, and 1 with the cordova-simulate menu (lets you choose the device, etc).

Only the 1st window (app) was opening, and I was seeing the same error messages as you in the Chrome inspector. Upon closing this window, only THEN did the 2nd window open.

I realize the 2nd window (cordova-simulate menu) is what fires the deviceready event.

Workaround: close the 1st window (app) after it errors out (deviceready has not fired...). The 2nd window should now open. Keep it open, open a new tab and navigate to http://localhost:whatever-port/index.html.

This is what worked for me. I'm on Windows 10 / Chrome.

**Comment by dotnetCarpenter** [comment]
According to @purplecabbage, this issue should be fixed in the upstream [cordova-serve](https://github.com/apache/cordova-serve) repo, which has no gihub issue list.

Ref: https://github.com/apache/cordova-browser/pull/31#issuecomment-309171231
