### ISSUE TITLE
How to rewrite URL in simulate Visual Studio

### ISSUE THREAD

**Issue by iamkarlson** [microsoft/cordova-simulate#248]
What I have is:
* Visual Studio 2017
* Cordova Project with TypeScript
* Angular 4.2.5

When I started the simulation and edited some files, typescript engine automatically recompiles them. After that simulation refreshes the browser. That leads to a broken page with "Cannot GET /menu".

How can I set url rewrtie for browser simulation when I'm using Visual Studio?

**Comment by jwargo** [comment]
Can you please provide some more details? What's causing the broken page? What would you want url rewrite to do?

**Comment by iamkarlson** [comment]
When you navigate to the app with specific URL route, app is trying to access to the path from this route (/menu in present scenario). But for my app this path defined in internal angular routing (refered to menu component). So, to let this angular routing work, I should enable url rewrite. Then my app will handle this routes.

**Comment by RedMickey** [comment]
Hi, we've added the [`spaurlrewrites`](https://github.com/microsoft/cordova-simulate#cli) parameter which is intended to improve page refreshing in single page applications. If this parameter is used, the Cordova-simulate tool will try to redirect a request with an unsupported by the server route to the `/index.html` page to reload the application without errors.
