### ISSUE TITLE
Implement file-transfer plugin

### ISSUE THREAD

**Issue by iamkarlson** [microsoft/cordova-simulate#253]
There's one very popular plugin for cordova. 

https://www.npmjs.com/package/cordova-plugin-file-transfer 

It would be great to have this plugin available out-of-the-box. Please consider making it available in cordova-simulate

**Comment by jwargo** [comment]
What would you want this plugin simulation to do?  I don't see the immediate value of this, all I can think it would do is send a progress value back to the calling program, but the file would still need to go somewhere (upload) or pull a file down (download), but how would that work?

You could always submit a pull request. :-)

**Comment by iamkarlson** [comment]
the best case just to let this plugin work. just at the first glance, I as new emulate user don't see real advantages without most of the popular plugins. because, if your app should be rewritten just to be debugged it's not OK in my opinion

**Comment by jwargo** [comment]
But what I'm asking is what would it simulate, and how?  What does a simulated version of the fie transfer plugin actually look like?  From an upload standpoint, I guess it could just take the file and discard it, returning success or failure through some sort of UI. What does download look like? You'd simulate the downloaded file and intercept the request?

**Comment by iamkarlson** [comment]
Why couldn't we make real work? I mean why we have to simulate that plugin? Can it be real file downloading and saving to the storage?

**Comment by themightychris** [comment]
As far as simulation features go, being able to rewrite URLs would be great, in order to redirect downloads/uploads to a testing server. That is, setting a number of search/replace regexs to run all URLs through

But, like @iamkarlson said just being able to test code that uses the plugin in the simulation environment would be great.
