### ISSUE TITLE
Camera config options GUI not implemented properly

### ISSUE THREAD

**Issue by andreszs** [Microsoft/cordova-simulate#254]
At the **Plugin Simulation** page, there's a **Camera** field item with 2 radio select options: `Prompt me for a file` and `Use this file:`. Whenever an option is selected, the other also remains selected, causing **both options to be active** in a scenario where only one of them can be used at a given time.

**Comment by jwargo** [comment]
it looks like it doesn't like the `cordova-panel-row` breaking up the radio button.
