### ISSUE TITLE
Plugin Simulation window rendering broken in Chrome browser

### ISSUE THREAD

**Issue by LayZeeDK** [Microsoft/cordova-simulate#259]
When opening the Plugin Simulation window in Chrome 64-bit version 64.0.3282.167 for Windows, it looks like this (see image).

![image](https://user-images.githubusercontent.com/6364586/36410284-5af824aa-1610-11e8-84f7-5455eaed11fa.png)

This deprecation warning occurs in the browser console:

> [Deprecation] /deep/ combinator is no longer supported in CSS dynamic profile.It is now effectively no-op, acting as if it were a descendant combinator. /deep/ combinator will be removed, and will be invalid at M65. You should remove it. See https://www.chromestatus.com/features/4964279606312960 for more details.

**Comment by Steckelfisch** [comment]
#metoo 
Ubuntu 17.10
Chrome Version 64.0.3282.186 (Official Build) (64-bit)

**Comment by jwargo** [comment]
#metoo Windows 10, latest Chrome.

**Comment by iTOYS** [comment]
Hi there,
Added PR with fixes for Chrome, could you please check it and give me result?

```bash
$ clone https://github.com/Microsoft/cordova-simulate.git
$ cd cordova-simulate
$ git checkout "fix/chrome-rendering"
$ npm install
$ ./bin/simulate ios --target chrome --dir "/path/to/your/project"
```

Thanks!

**Comment by LayZeeDK** [comment]
Looks good in  Chrome 64-bit version 66.0.3359.181 for Windows.
![image](https://user-images.githubusercontent.com/6364586/40314230-2ebd55d2-5d18-11e8-813f-f418fbfa1c5a.png)

Great job! Thank you 👏

**Comment by jwargo** [comment]
it's not working for me for some reason, doesn't recognize the project folder: 

```
~/dev/cordova-simulate(fix/chrome-rendering*) » ./bin/simulate browser --target chrome --dir "~/dev/test/" 

SIM WARNING: Error starting the simulation
SIM ERROR: Directory "~/dev/test/" does not appear to be in a Cordova project.
    at findProjectRoot (/Users/johnwargo/dev/cordova-simulate/node_modules/cordova-serve/src/platform.js:58:19)
    at /Users/johnwargo/dev/cordova-simulate/node_modules/cordova-serve/src/platform.js:40:27
    at _fulfilled (/Users/johnwargo/dev/cordova-simulate/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/Users/johnwargo/dev/cordova-simulate/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/Users/johnwargo/dev/cordova-simulate/node_modules/q/q.js:816:13)
    at /Users/johnwargo/dev/cordova-simulate/node_modules/q/q.js:877:14
    at runSingle (/Users/johnwargo/dev/cordova-simulate/node_modules/q/q.js:137:13)
    at flush (/Users/johnwargo/dev/cordova-simulate/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by jwargo** [comment]
@iTOYS works!

**Comment by iTOYS** [comment]
Awesome!
