### ISSUE TITLE
 onDeviceReady function not firing

### ISSUE THREAD

**Issue by jremi** [Microsoft/cordova-simulate#262]
I have a simple Cordova app setup, I just want to see the onDeviceReady fire the receivedEvent('deviceReady')... however nothing happens..

What do I need to configure to make this possible.

I am running the following from CLI:
`simulate ios --target chrome`

Any help appreciated.
Much thanks

**Comment by jwargo** [comment]
@jremi it's always easier to answer a question when we can see the code in question.

**Comment by iTOYS** [comment]
Close now. Feel free to reopen if you still have this issue!

Thanks!
