### ISSUE TITLE
Simulate Android in browser does not reload itself after a file change/save

### ISSUE THREAD

**Issue by Amosss** [Microsoft/cordova-simulate#263]
Hi

My launch.json section for simulating Android in browser looks like this:
{
"name": "Simulate Android in browser",
"type": "cordova",
"request": "launch",
"platform": "android",
"target": "chrome",
"simulatePort": 8000,
"livereload": true,
"sourceMaps": true,
"cwd": "${workspaceRoot}"
},

When making any changes in html/ts, nothing is happening on the browser side until I run ionic serve again. When doing so, a new browser/tab opens up with the changes and since then, the "play" also generates the "new" version.

When running in "run browser" mode, everything is updated as expected.
{
"name": "Run Browser",
"type": "cordova",
"request": "launch",
"platform": "browser",
"target": "chrome",
"simulatePort": 8000,
"livereload": true,
"sourceMaps": true,
"cwd": "${workspaceRoot}"
}

**Comment by jwargo** [comment]
@Amosss The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center] (https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
