### ISSUE TITLE
Viewport is full width

### ISSUE THREAD

**Issue by ph55** [Microsoft/cordova-simulate#273]
## Description

When I execute `simulate android` application width is always 100%.
![image](https://user-images.githubusercontent.com/1386622/41945530-603f80f2-79b6-11e8-8da0-7ae5c5b49caa.png)

And not like in example:
![image](https://user-images.githubusercontent.com/1386622/41945410-95bc5490-79b5-11e8-90d8-d7e1e555fa47.png)

## Steps to Reproduce
`npm install -g cordova-simulate`
`cordova create cordova-simulate`
`cd cordova-simulate`
`cordova platform add android`
`simulate android`

## Software versions
- `cordova-simulate` version: `0.4.0`
- OS platform and version: `OS: win32 x64 / Windows 10 Pro 1803`
- NodeJS version: `8.11.3`
- Cordova version: `8.0.0`
- Cordova-Android/iOS/Windows version: `7.0.0`
- List of installed plugins: `cordova-plugin-whitelist`

**Comment by TimBarham** [comment]
Thanks @ph55 - `cordova-simulate` needs a debug-host attached (like Visual Studio or Visual Studio Code) to do viewport sizing (it is implemented via the debug connection to Chrome). So unfortunately it is not supported via the command line.

**Comment by ph55** [comment]
@TimBarham Thanks, works in VSCode with dummy project.

But debugger stuck if I set `cwd` as nested directory. Any idea why ?
```json
        {
            "name": "devops.simulate.android",
            "type": "cordova",
            "request": "launch",
            "platform": "android",
            "target": "chrome",
            "simulatePort": 8000,
            "livereload": true,
            "sourceMaps": true,
            "cwd": "${workspaceRoot}/cordova/devops"
        }
```

Any plan for supporting Webstorm?

**Comment by TimBarham** [comment]
@ph55 - sounds like a question for the VSCode Cordova folk 😄 

Regarding WebStorm - I'm no longer actively involved with `cordova-simulate`, so I have no plans and am not aware of other plans. But it is OSS, so feel free to contribute! 😄
