### ISSUE TITLE
Integrate cli with chrome device toolbar

### ISSUE THREAD

**Issue by ph55** [microsoft/cordova-simulate#274]
## Description

Currently CLI doesn't support viewport sizing.
https://github.com/Microsoft/cordova-simulate/issues/273#issuecomment-400502297

Is it possible to integrate CLI with chrome dev-tools somehow ?
So if executed from CLI, devices would be mapped to available devices in dev-tools?

https://sites.google.com/a/chromium.org/chromedriver/mobile-emulation
![image](https://user-images.githubusercontent.com/1386622/41979761-846f1bf0-7a2d-11e8-97b6-e33efa256032.png)

Or it could just change windth and height in responsive mode
![image](https://user-images.githubusercontent.com/1386622/41980215-9ffbbdc8-7a2e-11e8-8f2a-ede33effbb57.png)

**Comment by EzioLi01** [comment]
Since we're using command line to launch browser rather than web driver, this argument for chrome is not available. Will do some investigations in the future, but will close it as not plan so far.
