### ISSUE TITLE
Latest release breaks xhr proxy

### ISSUE THREAD

**Issue by DaanSchuitmaker** [microsoft/cordova-simulate#291]
## Description
Latest release breaks xhr proxy for visual studio 2017 with a cordova project

## Steps to Reproduce
Create a cordova project for android
cordova 7.1.0
cordova-android 6.3.0

Setup Visual Studio 2017 with Tools for Cordova set XHR Proxy on.

Make an app with an XHR Call (an XHR Call wich breaks CORS rules)
Start simulate by running F5 with config Debug - Android - Simulate xxxx

## Software versions
- `cordova-simulate` version: 0.6.2
- OS platform and version: Windows 10 Ent
- NodeJS version: 10.15.3
- Cordova version: Global 8.1.2, project 7.1.0
- Cordova-Android/iOS/Windows version: 6.3.0/nvt/nvt
- List of installed plugins:nvt
- Does this reproduce on a debug build or release build? Both

**Comment by DaanSchuitmaker** [comment]
rolling back to 0.6.0 resolves the problems

**Comment by SounD120** [comment]
Hi @DaanSchuitmaker and thanks for reaching us. Is this issue reproduces on 0.6.1 version?

**Comment by DaanSchuitmaker** [comment]
> Hi @DaanSchuitmaker and thanks for reaching us. Is this issue reproduces on 0.6.1 version?

The 0.6.1 version is OK

**Comment by DaanSchuitmaker** [comment]
What i'm seeing in the chrome DevTools on the network tab is a whole lot of calls to live-reload-client.js
After that there is something what seems like a refresh at this point my xhr proxy is broken.

**Comment by SounD120** [comment]
@DaanSchuitmaker Сould you please give us more info about your problem with detailed step-by-step repro?

**Comment by DaanSchuitmaker** [comment]
Not really, 
My project was running fine yesterday and today this broke.

So the step by step would be:
- Use Visual Studio 2017
- VS - Tools - Options - Tools for Apache Cordova - Plugin Simulation
  Enable "Enable XHR Proxying"
- Create a VS Studio cordova App for android
  use cordova 7.1.0 with android platform 6.3.0

- create an simple App with a button on the push action add and XMLHttpRequest
  to a webservice i.a:
var xhr = new XMLHttpRequest();
xhr.open("get", "https://jsonplaceholder.typicode.com/todos/1");
xhr.onload = function(){
console.log(xhr.responseText);
};
xhr.send();

Build and run the app in chrome
Open the devtools
You should see a CORS notification
In the network tab you see a call to the url
without the proxy

**Comment by SounD120** [comment]
@DaanSchuitmaker We just tested fresh Cordova apps in Visual Studio 2017 created with global `cordova` versions 8.1.2 and 7.1.0 with `cordova-simulate` 0.6.2 and in both cases we couldn't reproduce your problem. Could you please share your project in which this issue is reproduced?

**Comment by SounD120** [comment]
Hi @DaanSchuitmaker . Do you have a chance to look at this?

**Comment by DaanSchuitmaker** [comment]
Not yet, I’m a bit pressured at work at this moment.
I’ll try to get you an example.


Daan Schuitmaker
Application Developer
t: +31742051199 | m: +31627334383
e: d.schuitmaker@dysel.com | w: www.dysel.com

**Comment by SounD120** [comment]
@DaanSchuitmaker  I use such configuration for the app: 
```
  "name": "BlankCordovaApp5",
  "version": "1.0.0",
  "private": true,
  "dependencies": {
    "cordova-android": "^6.3.0",
    "cordova-plugin-whitelist": "^1.2.2"
  },
  "cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {}
    },
    "platforms": [
      "android"
    ]
  }
```
I created the app via `cordova@7.1.0` and then updated cordova to 8.1.2
![image](https://user-images.githubusercontent.com/32372875/58409472-d0431980-8078-11e9-9c15-32104d0277de.png)

XHR Proxying is enabled and I ran application with such results:
![image](https://user-images.githubusercontent.com/32372875/58409676-3a5bbe80-8079-11e9-85f3-6826730d56ad.png)

**Comment by SounD120** [comment]
Hi @DaanSchuitmaker . Do you have a chance to look at this?

**Comment by DaanSchuitmaker** [comment]
I just upgraded my app but the same problem occurs.
Can i invite you for a skype meeting to show the problem?

**Comment by ruslan-bikkinin** [comment]
@DaanSchuitmaker yes, sure. Please, write to v-rubikk@microsoft.com (add v-yuskor@microsoft.com to recipients, as well) to arrange one.

**Comment by SounD120** [comment]
Hi, @DaanSchuitmaker . Is this issue is still relevant?

**Comment by DaanSchuitmaker** [comment]
Hi, @SounD120,
If made some changes in my Visual Studio Setup so it calls an older cordova version.
This way i have a working work around.

So this issue isn't relevant anymore.
Thnx for the effort.

**Comment by SounD120** [comment]
@DaanSchuitmaker Glad to hear that. Feel free to open new issues if you face any other issues.
