### ISSUE TITLE
Livereload doesn't work for Ionic 4 angular projects

### ISSUE THREAD

**Issue by ruslan-bikkinin** [microsoft/cordova-simulate#292]
## Description
See https://github.com/microsoft/vscode-cordova/issues/532#issuecomment-496563067 for more information about it.

## Expected behavior
Livereload works for Ionic 4 angular projects.

## Current behavior
Livereload doesn't work for Ionic 4 angular projects.

**Comment by ruslan-bikkinin** [comment]
Related Ionic issue: https://github.com/ionic-team/ionic-cli/issues/3999

**Comment by EzioLi01** [comment]
Close this issue since it caused by external issue, will follow that bug in ionic repo.
