### ISSUE TITLE
Edge browser not supported

### ISSUE THREAD

**Issue by Enpega** [microsoft/cordova-simulate#325]
## Description

Running simulate and specifying edge as target reports error.

## Steps to Reproduce

Command line:
simulate ios --target=edge
(Using browser instead of ios produces the same error)

## Actual Behavior
SIM ERROR: The browser target is not supported: edge
    at /usr/local/lib/node_modules/cordova-simulate/src/simulate.js:34:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

## Expected Behavior
The selected target browser to open the app for testing

## Software versions
- `cordova-simulate` version:
- OS platform and version: MacOS Catalina 10.15.6
- NodeJS version: 12.16.1
- Cordova version: 10.0.0
- Cordova-Android/iOS version: 6.0.0 / 6.1.0 
- List of installed plugins:
cordova-plugin-badge 0.8.6 "Badge"
cordova-plugin-device-motion 1.2.5 "Device Motion"
cordova-plugin-device-orientation 1.0.7 "Device Orientation"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-inappbrowser 4.0.0 "InAppBrowser"
cordova-plugin-keyboard 1.2.0 "Keyboard"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.1.3 "StatusBar"
cordova-plugin-whitelist 1.2.2 "Whitelist"

**Comment by EzioLi01** [comment]
Update related PR in cordova-serve repo, but not get any response so far.

**Comment by EzioLi01** [comment]
Plan to evaluate and add some supports for other browsers in this repo.

**Comment by EzioLi01** [comment]
Working on creating browser helper, close this issue.
