### ISSUE TITLE
[Feature] Add argument to prevent browser launch after simulating

### ISSUE THREAD

**Issue by CBR900cc** [microsoft/cordova-simulate#442]
## Description

Hello, I want to prevent open of browser when run "simulate android --target=chrome"

## Steps to Reproduce

simply run: simulate android --target=chrome

## Software versions
- `cordova-simulate` version: 1.2.0 latest
- OS platform and version: windows 10 22h2
- NodeJS version: 14.17.0
- Cordova version: 10.0.0

**Comment by CBR900cc** [comment]
I've temporaly solved by adding:
`cmd = 'cd'`
before:
`child_process.exec(cmd, opt, (err, stdout, stderr) => {`
in "C:/Users/<user>/AppData/Roaming/npm/node_modules/cordova-simulate/src/browsers/browse.js"

**Comment by EzioLi01** [comment]
Could you please share some information for your scenarios? Why we need to make browser not open?

**Comment by EzioLi01** [comment]
Hello @CBR900cc , do you have chance looking into this?

**Comment by CBR900cc** [comment]
> Could you please share some information for your scenarios? Why we need to make browser not open?

Hello @EzioLi01 I need that because during coding, I keep browser open with my default profile, and every time I run cmd command it launch new browser with a unknown profile and have to close new browser every time

**Comment by EzioLi01** [comment]
> > Could you please share some information for your scenarios? Why we need to make browser not open?
> 
> Hello @EzioLi01 I need that because during coding, I keep browser open with my default profile, and every time I run cmd command it launch new browser with a unknown profile and have to close new browser every time

Make sense, thanks for the clarification. Will look into this, any progress will comment here.

**Comment by EzioLi01** [comment]
Hey @CBR900cc, this feature is completed, we're adding `showbrowser` as an argument to handle this. It will be released on the next prod version, thank you!

**Comment by CBR900cc** [comment]
@EzioLi01 really good job, thanks for your effort
