### ISSUE TITLE
cordova-plugin-network-information defines a Windows-specific global clobber regadless of the platform

### ISSUE THREAD

**Issue by busykai** [Microsoft/cordova-simulate#53]
See [src/plugins/cordova-plugin-network-information/app-host-clobbers.js](https://github.com/Microsoft/cordova-simulate/blob/master/src/plugins/cordova-plugin-network-information/app-host-clobbers.js). `Windows` is a WinRT-specific global. It should be placed in `src/platforms/windows/app-host-clobbers.js` or otherwise be made Windows-specific.

CC: @albertinad

**Comment by albertinad** [comment]
Camera simulation plugin too defines app-host-clobbers for specific platform. https://github.com/Microsoft/cordova-simulate/blob/master/src/plugins/cordova-plugin-camera/app-host-clobbers.js
