### ISSUE TITLE
[bug][geolocation] Zoom level with wheel goes from 1 to 18 but with buttons from 0 to 21

### ISSUE THREAD

**Issue by digeff** [Microsoft/cordova-simulate#62]
I can only get to Zoom Levels: 1 to 18 by using the mouse wheel, but if I use the mouse buttons I can get to 0 and 21 also.

**Comment by albertinad** [comment]
@dlebu What do you think if we also change the (+) (-) buttons to a slider? That way we keep consistency with the other usages too.

**Comment by albertinad** [comment]
Fixed in #75
