### ISSUE TITLE
[confusing ui] I'm not sure what's the Go 16x button is for.

### ISSUE THREAD

**Issue by digeff** [Microsoft/cordova-simulate#63]
First time I used it I assume it might be the zoom level of the map.
It doesn't seem to be changing that, so now I'm guessing it's something related to the Navigator Simulator (probably the reproduction speed), but it'd be nice if the intent was clearer...

**Comment by dlebu** [comment]
@guillaumejenkins @albertinad I agree this can be misleading. Would it make sense to put the `Choose File` button in the same row as the `Go` and `16x` button?

**Comment by albertinad** [comment]
Yes! it would be much more clear.
