### ISSUE TITLE
[confusing UI] The widgets move to weird places when minimizing Device

### ISSUE THREAD

**Issue by digeff** [Microsoft/cordova-simulate#68]
Before minimizing:
![image](https://cloud.githubusercontent.com/assets/14098140/15944513/cbb54d4c-2e42-11e6-83a0-d54a054284cd.png)

After:
![image](https://cloud.githubusercontent.com/assets/14098140/15944547/daa2c1ae-2e42-11e6-89d0-ded52da3889e.png)

**Comment by dlebu** [comment]
@guillaumejenkins @albertinad Would we want to change this behavior? I believe the current design tries to fit all the components in the available space so I would call this `by design`.

**Comment by albertinad** [comment]
It is by design, if we need to classify this issue, it won't be a bug, but maybe an improvement or enhancement to consider later if it turns out that users find this hard or weird to use.
