### ISSUE TITLE
[weird behavior] In compass pressing the arrow down from 360 goes 359.99, 359, 358, etc...

### ISSUE THREAD

**Issue by digeff** [Microsoft/cordova-simulate#71]
In compass pressing the arrow down from 360 goes 359.99, 359, 358, etc...
![image](https://cloud.githubusercontent.com/assets/14098140/15948828/edc684f4-2e57-11e6-9b20-a9b72504cccf.png)
![image](https://cloud.githubusercontent.com/assets/14098140/15948833/f5c3ecfa-2e57-11e6-906f-ab3af338bff7.png)
![image](https://cloud.githubusercontent.com/assets/14098140/15948840/fe337d1a-2e57-11e6-8f49-904bea04f914.png)

**Comment by albertinad** [comment]
Fixed in #100

**Comment by albertinad** [comment]
@dlebu I noticed that this issue is scheduled for vNext milestone right now, but I already fixed it with a couple of more fixes related to the compass.

**Comment by dlebu** [comment]
@albertinad No problem. Thanks for the fixes!
