### ISSUE TITLE
[Suggestion] Double submit of "Choose file"

### ISSUE THREAD

**Issue by digeff** [microsoft/cordova-simulate#72]
If you click the "Choose file" button of the camera plugin really fast, it'll sometimes show the open file dialog multiple times in response. This could be an issue particularly in slow machines, if the user doesn't sees a response and clicks again. It'd be nice if the second instance could be automatically be omitted.

**Comment by drewgillies** [comment]
@paymicro Will you be submitting a PR?

**Comment by TimBarham** [comment]
@drewgillies - there is a PR (#232) which I have been looking at.

**Comment by EzioLi01** [comment]
Close this issue as comment in PR.
